spring.application.name=spring-microservice-L2

server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/effigo_projects
spring.datasource.username=postgres
spring.datasource.password=Martandpsql@03
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false